services:
  app:
    image: hntoplinks:latest
    ports:
      - "8067:8080"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:26773
      - SPRING_PROFILES_ACTIVE=localdocker
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=sa
      - DATABASE_NAME=hntoplinks
      - DATABASE_HOST=db
      - PORT=8080
    links:
      - db
  db:
    image: postgres:14.3
    ports:
      - "15433:5432"
    environment:
      - POSTGRES_PASSWORD=sa
      - POSTGRES_USER=sa
      - POSTGRES_DB=hntoplinks

