Vagrant.configure("2") do |config|
    config.vm.box = "fedora/36-cloud-base"
    config.vm.box_version = "36-20220504.1"
    config.ssh.username = 'root'
    config.ssh.port = 2222
    config.ssh.insert_key = 'true'  

    config.vm.network "forwarded_port", guest: 80, host: 8080
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
      end
    
  end